<option value="ABUT">ABUT</option>
    <option value="APALENG">APALENG</option>
    <option value="BACSIL">BACSIL</option>
    <option value="BANGBANGOLAN">BANGBANGOLAN</option>
    <option value="BANGCUSAY">BANGCUSAY</option>
    <option value="BARANGAY I (POB.)">BARANGAY I (POB.)</option>
    <option value="BARANGAY II (POB.)">BARANGAY II (POB.)</option>
    <option value="BARANGAY III (POB.)">BARANGAY III (POB.)</option>
    <option value="BARANGAY IV (POB.)">BARANGAY IV (POB.)</option>
    <option value="BARAOAS">BARAOAS</option>
    <option value="BATO">BATO</option>
    <option value="BIDAY">BIDAY</option>
    <option value="BIRUNGET">BIRUNGET</option>
    <option value="BUNGRO">BUNGRO</option>
    <option value="CABAROAN (NEGRO)">CABAROAN (NEGRO)</option>
    <option value="CABARSICAN">CABARSICAN</option>
    <option value="CADACLAN">CADACLAN</option>
    <option value="CALABUGAO">CALABUGAO</option>
    <option value="CAMANSI">CAMANSI</option>
    <option value="CANAOAY">CANAOAY</option>
    <option value="CARLATAN">CARLATAN</option>
    <option value="CATBANGEN">CATBANGEN</option>
    <option value="DALLANGAYAN ESTE">DALLANGAYAN ESTE</option>
    <option value="DALLANGAYAN OESTE">DALLANGAYAN OESTE</option>
    <option value="DALUMPINAS ESTE">DALUMPINAS ESTE</option>
    <option value="DALUMPINAS OESTE">DALUMPINAS OESTE</option>
    <option value="ILOCANOS NORTE">ILOCANOS NORTE</option>
    <option value="ILOCANOS SUR">ILOCANOS SUR</option>
    <option value="LANGCUAS">LANGCUAS</option>
    <option value="LINGSAT">LINGSAT</option>
    <option value="MADAYEGDEG">MADAYEGDEG</option>
    <option value="MAMELTAC">MAMELTAC</option>
    <option value="MASICONG">MASICONG</option>
    <option value="NAGYUBUYUBAN">NAGYUBUYUBAN</option>
    <option value="NAMTUTAN">NAMTUTAN</option>
    <option value="NARRA ESTE">NARRA ESTE</option>
    <option value="NARRA OESTE">NARRA OESTE</option>
    <option value="PACPACO">PACPACO</option>
    <option value="PAGDALAGAN">PAGDALAGAN</option>
    <option value="PAGDARAOAN">PAGDARAOAN</option>
    <option value="PAGUDPUD">PAGUDPUD</option>
    <option value="PAO NORTE">PAO NORTE</option>
    <option value="PAO SUR">PAO SUR</option>
    <option value="PARIAN">PARIAN</option>
    <option value="PIAS">PIAS</option>
    <option value="PORO">PORO</option>
    <option value="PUSPUS">PUSPUS</option>
    <option value="SACYUD">SACYUD</option>
    <option value="SAGAYAD">SAGAYAD</option>
    <option value="SAN AGUSTIN">SAN AGUSTIN</option>
    <option value="SAN FRANCISCO">SAN FRANCISCO</option>
    <option value="SAN VICENTE">SAN VICENTE</option>
    <option value="SANTIAGO NORTE">SANTIAGO NORTE</option>
    <option value="SANTIAGO SUR">SANTIAGO SUR</option>
    <option value="SAOAY">SAOAY</option>
    <option value="SEVILLA">SEVILLA</option>
    <option value="SIBOAN-OTONG">SIBOAN-OTONG</option>
    <option value="TANQUI">TANQUI</option>
    <option value="TANQUIGAN">TANQUIGAN</option>